[package]
name = "infraweave-mcp"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
rmcp-openapi = { workspace = true }
rmcp = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
utoipa = { workspace = true }
webserver-openapi = { path = "../webserver-openapi", default-features = false }
rand = { workspace = true }
