[package]
name = "crd_templator"
version = "0.1.0"
edition = "2021"
license-file = "../LICENSE"

[dependencies]
serde = { workspace = true }
serde_yaml = { workspace = true }
tera = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }

env_defs = { path = "../defs" }

[lib]
name = "crd_templator"
path = "src/lib.rs"
